server:
  port: 8888

spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, metrics, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
