apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: CHANGE_ME/biddy-product:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: biddy-common-config
            - secretRef:
                name: biddy-secret
          volumeMounts:
            - name: product-images
              mountPath: /app/images
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 45
            periodSeconds: 10
      volumes:
        - name: product-images
          emptyDir: {}

