apiVersion: v1
kind: ConfigMap
metadata:
  name: biddy-common-config
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "15432"
  POSTGRES_DB: postgres
  MEMBER_DB: biddy_member
  PRODUCT_DB: biddy_product
  SEARCH_DB: biddy_search
  ORDER_DB: biddy_order
  AUCTION_DB: biddy_auction
  PAYMENT_DB: biddy_payment
  CHAT_DB: biddy_chat
  CHATBOT_DB: biddy_chatbot
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka/
  SPRING_CLOUD_CONFIG_URI: http://config:8888
  ORDER_SERVICE_URL: http://order:8083
  PRODUCT_SERVICE_URL: http://product:8082
  SEARCH_SERVICE_URL: http://search:8087
  SEARCH_CANDIDATE_SIZE: "30"
  SEARCH_RECOMMENDATION_SIZE: "2"
  SEARCH_HISTORY_KEYWORD_SIZE: "5"
  LLM_ENABLED: "true"
  ELASTICSEARCH_URIS: http://elasticsearch:9200
  TOSS_PAYMENTS_BASE_URL: https://api.tosspayments.com
  TZ: Asia/Seoul
  JAVA_TOOL_OPTIONS: -Duser.timezone=Asia/Seoul
  IMAGE_BASE_URL: https://team03-biddy-storage.s3.ap-northeast-2.amazonaws.com
  AWS_S3_BUCKET: team03-biddy-storage
  AWS_S3_REGION: ap-northeast-2
