apiVersion: v1
kind: Secret
metadata:
  name: biddy-secret
type: Opaque
stringData:
  POSTGRES_USER: CHANGE_ME
  POSTGRES_PASSWORD: CHANGE_ME
  JWT_SECRET: CHANGE_ME
  MAIL_USERNAME: CHANGE_ME
  MAIL_PASSWORD: CHANGE_ME
  TOSS_PAYMENTS_SECRET_KEY: CHANGE_ME
  GEMINI_API_KEY: CHANGE_ME
  OPENAI_API_KEY: CHANGE_ME
