apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: config
          image: ghcr.io/prgrms-be-adv-devcourse/config:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          envFrom:
            - configMapRef:
                name: biddy-common-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 10

