apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb
data:
  01-create-databases.sql: |
    CREATE DATABASE biddy_member;

    CREATE DATABASE biddy_product;
    \connect biddy_product
    CREATE EXTENSION IF NOT EXISTS vector;

    CREATE DATABASE biddy_order;
    CREATE DATABASE biddy_auction;
    CREATE DATABASE biddy_payment;
    CREATE DATABASE biddy_chat;
    CREATE DATABASE biddy_chatbot;
