---
# Service: K8s 내부에서 'postgres:5432'로 접근
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: biddy
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP

---
# Endpoint: Docker 호스트 IP를 지정
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres
  namespace: biddy
subsets:
  - addresses:
      - ip: 10.0.30.99  # AWS EC2 Private IP
    ports:
      - name: postgres
        port: 5432
        protocol: TCP
