apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: biddy-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - 43.202.187.240.nip.io
      secretName: biddy-api-tls
  rules:
    - host: 43.202.187.240.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apigateway
                port:
                  number: 8000
