apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery
  namespace: biddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery
  template:
    metadata:
      labels:
        app: discovery
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8761"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: discovery
          image: ghcr.io/prgrms-be-adv-devcourse/frontal-discovery:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

